# Generated by Django 4.2.9 on 2024-02-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
